// All the motor definitions
#define PORT_DRIVERIGHTBACK 1
#define PORT_DRIVERIGHTFRONT 2
#define PORT_FLYWHEEL 3
#define PORT_DRIVELEFTBACK 5
#define PORT_DRIVELEFTCENTER 6
#define PORT_INDEXER 8
#define PORT_VISION 9
#define PORT_DRIVERIGHTCENTER 4
#define PORT_DRIVELEFTFRONT 7

#define HIGHFLAGPOWER 122 //125
#define HIGHFLAGRPM 102
#define MIDDLEFLAGPOWER 71 //77
#define MIDDLEFLAGRPM 62
#define BETWEENFLAGPOWER 103
#define BETWEEENFLAGRPM 90

#define FRONTTILEPOWER 98
#define FRONTTILERPM 75
#define BACKTILEPOWER 100
#define BACKTILERPM 90

#define LIMITSWITCHPORT 1

#define OVERRIDETEMP true
#define MAXALLOWEDTEMP 45

#define NUM_VISION_OBJECTS 2
#define VISIONTARGETSIG 1
#define REDFLAGSIG 2
#define BLUEFLAGSIG 3
#define FLAGPIXELHEIGHT 46
#define ANGLETOLERANCE 20
#define HEIGHTTOLERANCE 5

#define KPFLYWHEEL 0.5
#define KIFLYWHEEL 0.05

#define EXTRAPOWER 10
#define FRICTIONPOWER 0

#define DIFFBRAKE 2

extern int autonNumber;
extern bool redAlliance;
