// All the motor definitions
#define PORT_DRIVELEFTFRONT 1
#define PORT_DRIVERIGHTFRONT 2
#define PORT_FLYWHEEL 3
#define PORT_INTAKE 4
#define PORT_DRIVELEFTBACK 5
#define PORT_DRIVERIGHTBACK 6
#define PORT_CAPLIFT 7
#define PORT_VISION 9